INSERT INTO films (title, director, release_year, genre, description) VALUES
('Persona', 'Ingmar Bergman', 1966, 'Drama', 'A nurse is put in charge of a mute actress and finds that their personalities are melding together in disturbing ways.'),
('The Seventh Seal', 'Ingmar Bergman', 1957, 'Fantasy', 'A knight returning from the Crusades seeks answers about life, death, and the existence of God as he plays chess with Death itself.'),
('Stalker', 'Andrei Tarkovsky', 1979, 'Sci-Fi', 'A guide leads two men through a mysterious Zone to find a room that grants their deepest desires.'),
('Breathless', 'Jean-Luc Godard', 1960, 'Crime/Drama', 'A young car thief kills a policeman and tries to persuade a girl to run away with him to Italy.'),
('The Mirror', 'Andrei Tarkovsky', 1975, 'Drama/Autobiographical', 'A fragmented reflection of a man\'s memories, dreams, and poetry throughout his life, blending personal and historical events.'),
('Blue Velvet', 'David Lynch', 1986, 'Mystery/Thriller', 'A college student discovers a severed ear in a field and uncovers a sinister mystery involving a beautiful nightclub singer and a psychopathic criminal.'),
('The Grand Budapest Hotel', 'Wes Anderson', 2014, 'Comedy/Drama', 'The adventures of a legendary concierge and his protégé as they become embroiled in a theft, a murder, and a pursuit through Europe.'),
('Eraserhead', 'David Lynch', 1977, 'Horror', 'A surreal and nightmarish look at a man grappling with fatherhood, alienation, and a deeply unsettling environment.'),
('La Dolce Vita', 'Federico Fellini', 1960, 'Drama', 'A journalist navigates the opulence and depravity of Rome\'s elite while questioning the meaning of his life.'),
('Chungking Express', 'Wong Kar-wai', 1994, 'Romance/Drama', 'Two melancholic Hong Kong policemen cross paths with enigmatic women who alter their lives in profound ways.'),
('The Lobster', 'Yorgos Lanthimos', 2015, 'Romance/Sci-Fi', 'In a dystopian society, single people are turned into animals if they fail to find a partner within 45 days.'),
('Amélie', 'Jean-Pierre Jeunet', 2001, 'Romance/Comedy', 'A shy Parisian waitress decides to change the lives of those around her while grappling with her own loneliness.'),
('Moonlight', 'Barry Jenkins', 2016, 'Drama', 'A chronicle of a young African-American man’s struggle with his identity and sexuality in a rough Miami neighborhood.'),
('Parasite', 'Bong Joon-ho', 2019, 'Thriller/Drama', 'A poor family schemes to become employed by a wealthy household by infiltrating their lives through deceit.'),
('A Ghost Story', 'David Lowery', 2017, 'Drama/Fantasy', 'A spectral figure observes the lives of his loved ones and the passing of time after his untimely death.');